name: Check

on:
  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with: 
          java-version: 11

      # Run Maven Verify
      - name: Run Maven Verify
        run: mvn clean verify
