name: Check

on:
  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository
      - uses: actions/checkout@v2

      # Set-up JDK
      - name: Set-up JDK
        uses: actions/setup-java@v1
        with: 
          java-version: 11
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
 
      # Maven Verify
      - name: Run Verify
        run: mvn verify
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
